apiVersion: batch/v1
kind: CronJob
metadata:
  name: hacknews-cronjob
spec:
  schedule: "0 6,12,20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hacknews-cronjob
            image: hacknews:v0.0.1
            command: ["python", "/app/main_hacknews_job.py"]  # 如果你有不同的命令，可以调整这里
            envFrom:
            - configMapRef:
                name: github-agent-config
          restartPolicy: OnFailure