apiVersion: v1
kind: ConfigMap
metadata:
  name: github-agent-config
data:
  MY_ENV_VAR_1: "value1"
  MY_ENV_VAR_2: "value2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-agent-server
  labels:
    app: github-agent-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-agent-server
  template:
    metadata:
      labels:
        app: github-agent-server
    spec:
      containers:
        - name: github-agent-server-container
          image: github-agent-server:v0.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: github-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: github-agent-server
spec:
  selector:
    app: github-agent-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: github-agent-server
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`74.121.149.207`) && PathPrefix(`/github`)
    services:
    - name: github-agent-server
      port: 80
